"""
Visualization Generator for Audio-Visual Adversarial Attack Results

This script reads the audiovisualresults.txt file generated by final_audio_visual_attack.py
and creates a comprehensive set of visualizations for research analysis.

Usage:
    python adversarial_attacks/create_visualizations.py --results-file ./final_audiovisualattack/audiovisualresults.txt
    python adversarial_attacks/create_visualizations.py --results-dir ./final_audiovisualattack
"""

import sys
from pathlib import Path
import numpy as np
import argparse
import re
from typing import Dict, List, Any, Tuple

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import matplotlib
matplotlib.use('Agg')

try:
    import cv2
    CV2_AVAILABLE = True
except ImportError:
    CV2_AVAILABLE = False
    print("Warning: OpenCV (cv2) not available. MSE visualization will be skipped.")

# Set style for publication-quality figures
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['font.size'] = 11
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['legend.fontsize'] = 10
plt.rcParams['figure.dpi'] = 150


def parse_results_file(filepath: Path) -> Dict[str, Any]:
    """
    Parse the audiovisualresults.txt file and extract all data.
    
    Returns a dictionary with:
    - config: experiment configuration
    - aggregate: aggregate statistics
    - samples: per-sample data as list of dicts
    - arrays: raw data arrays
    """
    with open(filepath, 'r') as f:
        content = f.read()
    
    data = {
        'config': {},
        'aggregate': {},
        'samples': [],
        'arrays': {}
    }
    
    # Parse configuration section
    config_match = re.search(r'\[Video Attack Parameters\](.*?)\[Audio Attack Parameters\](.*?)\[General\](.*?)(?=\n=)', 
                             content, re.DOTALL)
    if config_match:
        for line in config_match.group(1).strip().split('\n'):
            if '=' in line:
                key, val = line.split('=', 1)
                data['config'][f'video_{key.strip()}'] = val.strip()
        for line in config_match.group(2).strip().split('\n'):
            if '=' in line:
                key, val = line.split('=', 1)
                data['config'][f'audio_{key.strip()}'] = val.strip()
        for line in config_match.group(3).strip().split('\n'):
            if '=' in line:
                key, val = line.split('=', 1)
                data['config'][key.strip()] = val.strip()
    
    # Parse aggregate statistics
    sections = [
        'Success Rates', 'Confidence Change Statistics', 
        'Real Probability Statistics', 'Perturbation Statistics',
        'Timing Statistics', 'Best Attack Per Sample'
    ]
    for section in sections:
        pattern = rf'\[{section}\](.*?)(?=\n\[|\n=)'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            for line in match.group(1).strip().split('\n'):
                if '=' in line:
                    key, val = line.split('=', 1)
                    try:
                        data['aggregate'][key.strip()] = float(val.strip())
                    except ValueError:
                        data['aggregate'][key.strip()] = val.strip()
    
    # Parse CSV data
    csv_match = re.search(r'PER-SAMPLE DATA.*?\n\n(sample_id.*?)(?=\n\n=)', content, re.DOTALL)
    if csv_match:
        lines = csv_match.group(1).strip().split('\n')
        if lines:
            headers = lines[0].split(',')
            for line in lines[1:]:
                if line.strip():
                    values = line.split(',')
                    sample = {}
                    for h, v in zip(headers, values):
                        try:
                            if '.' in v:
                                sample[h] = float(v)
                            elif v.isdigit():
                                sample[h] = int(v)
                            else:
                                sample[h] = v
                        except:
                            sample[h] = v
                    data['samples'].append(sample)
    
    # Parse raw arrays
    array_patterns = {
        'original_probs': r'original_probs\s*=\s*\[(.*?)\]',
        'video_only_probs': r'video_only_probs\s*=\s*\[(.*?)\]',
        'audio_only_probs': r'audio_only_probs\s*=\s*\[(.*?)\]',
        'combined_probs': r'combined_probs\s*=\s*\[(.*?)\]',
        'video_only_changes': r'video_only_changes\s*=\s*\[(.*?)\]',
        'audio_only_changes': r'audio_only_changes\s*=\s*\[(.*?)\]',
        'combined_changes': r'combined_changes\s*=\s*\[(.*?)\]',
        'video_only_successes': r'video_only_successes\s*=\s*\[(.*?)\]',
        'audio_only_successes': r'audio_only_successes\s*=\s*\[(.*?)\]',
        'combined_successes': r'combined_successes\s*=\s*\[(.*?)\]',
        'video_linf_norms': r'video_linf_norms\s*=\s*\[(.*?)\]',
        'video_l2_norms': r'video_l2_norms\s*=\s*\[(.*?)\]',
        'audio_linf_norms': r'audio_linf_norms\s*=\s*\[(.*?)\]',
        'audio_snr_dbs': r'audio_snr_dbs\s*=\s*\[(.*?)\]',
        'video_times': r'video_times\s*=\s*\[(.*?)\]',
        'audio_times': r'audio_times\s*=\s*\[(.*?)\]',
        'total_times': r'total_times\s*=\s*\[(.*?)\]',
    }
    
    for name, pattern in array_patterns.items():
        match = re.search(pattern, content)
        if match:
            values = [float(x.strip()) for x in match.group(1).split(',') if x.strip()]
            data['arrays'][name] = np.array(values)
    
    return data


def create_asr_bar_chart(data: Dict, output_path: Path):
    """Create Attack Success Rate (ASR) comparison bar chart."""
    agg = data['aggregate']
    
    video_asr = agg.get('video_only_success_rate', 0) * 100
    audio_asr = agg.get('audio_only_success_rate', 0) * 100
    combined_asr = agg.get('combined_success_rate', 0) * 100
    
    fig, ax = plt.subplots(figsize=(8, 6))
    
    attacks = ['Video-Only', 'Audio-Only', 'Combined']
    asrs = [video_asr, audio_asr, combined_asr]
    colors = ['#3498db', '#2ecc71', '#e74c3c']
    
    bars = ax.bar(attacks, asrs, color=colors, edgecolor='black', linewidth=1.5, width=0.6)
    
    # Add value labels on bars
    for bar, asr in zip(bars, asrs):
        height = bar.get_height()
        ax.annotate(f'{asr:.1f}%',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 5),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=14, fontweight='bold')
    
    ax.set_ylabel('Attack Success Rate (%)', fontsize=12)
    ax.set_title('Attack Success Rate Comparison', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 110)
    ax.axhline(y=50, color='gray', linestyle='--', alpha=0.5, label='50% threshold')
    
    # Add sample count
    n = int(agg.get('video_only_success_count', 0) + 
            (agg.get('video_only_success_rate', 0) > 0 and 
             agg.get('video_only_success_count', 0) / agg.get('video_only_success_rate', 1)))
    if 'video_only_success_rate' in agg and agg['video_only_success_rate'] > 0:
        n = int(agg['video_only_success_count'] / agg['video_only_success_rate'])
    ax.text(0.02, 0.98, f'n = {len(data["samples"])} samples', transform=ax.transAxes, 
            fontsize=10, verticalalignment='top')
    
    plt.tight_layout()
    plt.savefig(output_path / 'asr_comparison.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: asr_comparison.png")


def create_confidence_change_boxplot(data: Dict, output_path: Path):
    """Create box plot comparing confidence changes across attack types."""
    arrays = data['arrays']
    
    fig, ax = plt.subplots(figsize=(10, 6))
    
    box_data = [
        arrays.get('video_only_changes', []),
        arrays.get('audio_only_changes', []),
        arrays.get('combined_changes', [])
    ]
    
    bp = ax.boxplot(box_data, labels=['Video-Only', 'Audio-Only', 'Combined'],
                    patch_artist=True, notch=True)
    
    colors = ['#3498db', '#2ecc71', '#e74c3c']
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)
    
    # Add individual points
    for i, d in enumerate(box_data):
        x = np.random.normal(i + 1, 0.04, size=len(d))
        ax.scatter(x, d, alpha=0.4, color='black', s=20, zorder=3)
    
    ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    ax.set_ylabel('Confidence Change (Δ Real Probability)', fontsize=12)
    ax.set_title('Distribution of Confidence Changes by Attack Type', fontsize=14, fontweight='bold')
    
    # Add mean values as text
    for i, d in enumerate(box_data):
        if len(d) > 0:
            mean_val = np.mean(d)
            ax.annotate(f'μ={mean_val:.3f}', xy=(i + 1, np.max(d) + 0.02),
                       ha='center', fontsize=9)
    
    plt.tight_layout()
    plt.savefig(output_path / 'confidence_change_boxplot.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: confidence_change_boxplot.png")


def create_probability_trajectory_plot(data: Dict, output_path: Path):
    """Create line plot showing probability changes per sample."""
    arrays = data['arrays']
    n_samples = len(arrays.get('original_probs', []))
    
    if n_samples == 0:
        return
    
    fig, ax = plt.subplots(figsize=(12, 6))
    
    x = np.arange(1, n_samples + 1)
    
    ax.plot(x, arrays['original_probs'], 'ko-', label='Original', markersize=6, linewidth=1.5)
    ax.plot(x, arrays['video_only_probs'], 's--', color='#3498db', label='Video-Only', 
            markersize=6, linewidth=1.5, alpha=0.8)
    ax.plot(x, arrays['audio_only_probs'], '^--', color='#2ecc71', label='Audio-Only', 
            markersize=6, linewidth=1.5, alpha=0.8)
    ax.plot(x, arrays['combined_probs'], 'D-', color='#e74c3c', label='Combined', 
            markersize=6, linewidth=2)
    
    ax.axhline(y=0.5, color='orange', linestyle='--', linewidth=2, alpha=0.7, label='Success Threshold')
    ax.fill_between(x, 0.5, 1, alpha=0.1, color='green', label='Success Region')
    
    ax.set_xlabel('Sample Index', fontsize=12)
    ax.set_ylabel('Real Probability (P(real))', fontsize=12)
    ax.set_title('Probability Trajectory Across Samples', fontsize=14, fontweight='bold')
    ax.set_xlim(0.5, n_samples + 0.5)
    ax.set_ylim(0, 1.05)
    ax.legend(loc='upper right', ncol=2)
    ax.set_xticks(x)
    
    plt.tight_layout()
    plt.savefig(output_path / 'probability_trajectory.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: probability_trajectory.png")


def create_perturbation_analysis_plot(data: Dict, output_path: Path):
    """Create visualization of perturbation magnitudes."""
    arrays = data['arrays']
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    # Video L-inf norm distribution
    if 'video_linf_norms' in arrays:
        ax = axes[0]
        ax.hist(arrays['video_linf_norms'], bins=15, color='#3498db', edgecolor='black', alpha=0.7)
        ax.axvline(np.mean(arrays['video_linf_norms']), color='red', linestyle='--', 
                   label=f'Mean: {np.mean(arrays["video_linf_norms"]):.4f}')
        ax.set_xlabel('Video L∞ Norm', fontsize=11)
        ax.set_ylabel('Frequency', fontsize=11)
        ax.set_title('Video Perturbation Distribution', fontsize=12, fontweight='bold')
        ax.legend()
    
    # Audio L-inf norm distribution
    if 'audio_linf_norms' in arrays:
        ax = axes[1]
        ax.hist(arrays['audio_linf_norms'], bins=15, color='#2ecc71', edgecolor='black', alpha=0.7)
        ax.axvline(np.mean(arrays['audio_linf_norms']), color='red', linestyle='--',
                   label=f'Mean: {np.mean(arrays["audio_linf_norms"]):.4f}')
        ax.set_xlabel('Audio L∞ Norm', fontsize=11)
        ax.set_ylabel('Frequency', fontsize=11)
        ax.set_title('Audio Perturbation Distribution', fontsize=12, fontweight='bold')
        ax.legend()
    
    # Audio SNR distribution
    if 'audio_snr_dbs' in arrays:
        ax = axes[2]
        ax.hist(arrays['audio_snr_dbs'], bins=15, color='#9b59b6', edgecolor='black', alpha=0.7)
        ax.axvline(np.mean(arrays['audio_snr_dbs']), color='red', linestyle='--',
                   label=f'Mean: {np.mean(arrays["audio_snr_dbs"]):.1f} dB')
        ax.set_xlabel('Audio SNR (dB)', fontsize=11)
        ax.set_ylabel('Frequency', fontsize=11)
        ax.set_title('Audio Quality (SNR) Distribution', fontsize=12, fontweight='bold')
        ax.legend()
    
    plt.tight_layout()
    plt.savefig(output_path / 'perturbation_analysis.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: perturbation_analysis.png")


def create_perturbation_vs_effectiveness_scatter(data: Dict, output_path: Path):
    """Scatter plot: perturbation magnitude vs attack effectiveness."""
    arrays = data['arrays']
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Video: L-inf vs confidence change
    if 'video_linf_norms' in arrays and 'video_only_changes' in arrays:
        ax = axes[0]
        colors = ['green' if s else 'red' for s in arrays.get('video_only_successes', [])]
        ax.scatter(arrays['video_linf_norms'], arrays['video_only_changes'], 
                   c=colors, s=80, alpha=0.7, edgecolors='black')
        ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
        
        # Add trend line
        z = np.polyfit(arrays['video_linf_norms'], arrays['video_only_changes'], 1)
        p = np.poly1d(z)
        x_line = np.linspace(min(arrays['video_linf_norms']), max(arrays['video_linf_norms']), 100)
        ax.plot(x_line, p(x_line), 'b--', alpha=0.5, label='Trend')
        
        ax.set_xlabel('Video L∞ Perturbation', fontsize=11)
        ax.set_ylabel('Confidence Change', fontsize=11)
        ax.set_title('Video: Perturbation vs Effectiveness', fontsize=12, fontweight='bold')
        
        # Legend
        success_patch = mpatches.Patch(color='green', label='Success')
        fail_patch = mpatches.Patch(color='red', label='Failure')
        ax.legend(handles=[success_patch, fail_patch])
    
    # Audio: SNR vs confidence change
    if 'audio_snr_dbs' in arrays and 'audio_only_changes' in arrays:
        ax = axes[1]
        colors = ['green' if s else 'red' for s in arrays.get('audio_only_successes', [])]
        ax.scatter(arrays['audio_snr_dbs'], arrays['audio_only_changes'], 
                   c=colors, s=80, alpha=0.7, edgecolors='black')
        ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
        
        # Add trend line
        z = np.polyfit(arrays['audio_snr_dbs'], arrays['audio_only_changes'], 1)
        p = np.poly1d(z)
        x_line = np.linspace(min(arrays['audio_snr_dbs']), max(arrays['audio_snr_dbs']), 100)
        ax.plot(x_line, p(x_line), 'b--', alpha=0.5, label='Trend')
        
        ax.set_xlabel('Audio SNR (dB) - Higher = Less Perturbed', fontsize=11)
        ax.set_ylabel('Confidence Change', fontsize=11)
        ax.set_title('Audio: Quality vs Effectiveness', fontsize=12, fontweight='bold')
        
        success_patch = mpatches.Patch(color='green', label='Success')
        fail_patch = mpatches.Patch(color='red', label='Failure')
        ax.legend(handles=[success_patch, fail_patch])
    
    plt.tight_layout()
    plt.savefig(output_path / 'perturbation_vs_effectiveness.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: perturbation_vs_effectiveness.png")


def create_best_attack_pie_chart(data: Dict, output_path: Path):
    """Pie chart showing which attack performed best per sample."""
    agg = data['aggregate']
    
    video_best = int(agg.get('video_best_count', 0))
    audio_best = int(agg.get('audio_best_count', 0))
    combined_best = int(agg.get('combined_best_count', 0))
    
    total = video_best + audio_best + combined_best
    if total == 0:
        return
    
    fig, ax = plt.subplots(figsize=(8, 8))
    
    sizes = [video_best, audio_best, combined_best]
    labels = [f'Video-Only\n({video_best})', f'Audio-Only\n({audio_best})', f'Combined\n({combined_best})']
    colors = ['#3498db', '#2ecc71', '#e74c3c']
    explode = (0.02, 0.02, 0.05)  # Slightly explode combined
    
    wedges, texts, autotexts = ax.pie(sizes, explode=explode, labels=labels, colors=colors,
                                       autopct='%1.1f%%', startangle=90,
                                       textprops={'fontsize': 11})
    
    for autotext in autotexts:
        autotext.set_fontweight('bold')
    
    ax.set_title('Best Performing Attack Per Sample', fontsize=14, fontweight='bold')
    
    plt.tight_layout()
    plt.savefig(output_path / 'best_attack_distribution.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: best_attack_distribution.png")


def create_timing_analysis_plot(data: Dict, output_path: Path):
    """Bar chart of attack timing."""
    arrays = data['arrays']
    
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    # Average timing comparison
    ax = axes[0]
    attack_types = ['Video\nAttack', 'Audio\nAttack', 'Total']
    times = [
        np.mean(arrays.get('video_times', [0])),
        np.mean(arrays.get('audio_times', [0])),
        np.mean(arrays.get('total_times', [0]))
    ]
    colors = ['#3498db', '#2ecc71', '#95a5a6']
    
    bars = ax.bar(attack_types, times, color=colors, edgecolor='black')
    for bar, t in zip(bars, times):
        ax.annotate(f'{t:.1f}s', xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
                    xytext=(0, 5), textcoords='offset points', ha='center', fontsize=11)
    
    ax.set_ylabel('Time (seconds)', fontsize=11)
    ax.set_title('Average Attack Time', fontsize=12, fontweight='bold')
    
    # Per-sample timing stacked bar
    ax = axes[1]
    n_samples = len(arrays.get('video_times', []))
    if n_samples > 0:
        x = np.arange(1, n_samples + 1)
        video_t = arrays.get('video_times', np.zeros(n_samples))
        audio_t = arrays.get('audio_times', np.zeros(n_samples))
        
        ax.bar(x, video_t, label='Video Attack', color='#3498db', edgecolor='black')
        ax.bar(x, audio_t, bottom=video_t, label='Audio Attack', color='#2ecc71', edgecolor='black')
        
        ax.set_xlabel('Sample Index', fontsize=11)
        ax.set_ylabel('Time (seconds)', fontsize=11)
        ax.set_title('Per-Sample Attack Time', fontsize=12, fontweight='bold')
        ax.legend()
        ax.set_xticks(x)
    
    plt.tight_layout()
    plt.savefig(output_path / 'timing_analysis.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: timing_analysis.png")


def calculate_video_mse(original_path: Path, adversarial_path: Path) -> float:
    """
    Calculate Mean Squared Error between original and adversarial video frames.
    
    Args:
        original_path: Path to original video file
        adversarial_path: Path to adversarial video file
        
    Returns:
        Mean MSE across all frames, or None if calculation fails
    """
    if not CV2_AVAILABLE:
        return None
    
    if not original_path.exists() or not adversarial_path.exists():
        return None
    
    try:
        cap_orig = cv2.VideoCapture(str(original_path))
        cap_adv = cv2.VideoCapture(str(adversarial_path))
        
        mse_values = []
        
        while True:
            ret_orig, frame_orig = cap_orig.read()
            ret_adv, frame_adv = cap_adv.read()
            
            if not ret_orig or not ret_adv:
                break
            
            # Convert to float for MSE calculation
            frame_orig = frame_orig.astype(np.float64)
            frame_adv = frame_adv.astype(np.float64)
            
            # Calculate MSE for this frame
            mse = np.mean((frame_orig - frame_adv) ** 2)
            mse_values.append(mse)
        
        cap_orig.release()
        cap_adv.release()
        
        if mse_values:
            return np.mean(mse_values)
        return None
        
    except Exception as e:
        print(f"    Warning: Could not calculate MSE: {e}")
        return None


def collect_mse_data(results_dir: Path, n_samples: int) -> List[float]:
    """
    Collect MSE values from all sample directories.
    
    Args:
        results_dir: Base results directory (e.g., ./final_audiovisualattack)
        n_samples: Number of samples to check
        
    Returns:
        List of MSE values (None for samples where calculation failed)
    """
    mse_values = []
    
    for i in range(1, n_samples + 1):
        sample_dir = results_dir / f"sample_{i}"
        original_video = sample_dir / "02_original_video_processed.mp4"
        adversarial_video = sample_dir / "04_adversarial_video.mp4"
        
        mse = calculate_video_mse(original_video, adversarial_video)
        mse_values.append(mse)
    
    return mse_values


def create_mse_vs_probability_change_scatter(data: Dict, output_path: Path, results_dir: Path):
    """
    Create scatter plot of MSE vs probability change for combined attacks.
    
    This visualization shows the relationship between the amount of visual
    perturbation (measured by MSE) and the effectiveness of the attack
    (measured by probability change).
    """
    if not CV2_AVAILABLE:
        print("  Skipped: mse_vs_probability_change.png (OpenCV not available)")
        return
    
    arrays = data['arrays']
    n_samples = len(data['samples'])
    
    if n_samples == 0:
        print("  Skipped: mse_vs_probability_change.png (no samples)")
        return
    
    print("  Calculating MSE values from video files...")
    mse_values = collect_mse_data(results_dir, n_samples)
    
    # Use video-only attack data (MSE is a video metric)
    if 'video_only_changes' not in arrays:
        print("  Skipped: mse_vs_probability_change.png (no video probability change data)")
        return
    
    prob_changes = arrays['video_only_changes']
    successes_raw = arrays.get('video_only_successes', np.array([]))
    
    # Convert successes to boolean list (handles numpy arrays with 1.0/0.0)
    successes = [bool(s) for s in successes_raw] if len(successes_raw) > 0 else [False] * len(prob_changes)
    
    # Filter out None MSE values and align data
    valid_indices = [i for i, mse in enumerate(mse_values) if mse is not None]
    
    if len(valid_indices) == 0:
        print("  Skipped: mse_vs_probability_change.png (could not calculate MSE for any sample)")
        return
    
    # Only include indices that exist in all arrays
    valid_indices = [i for i in valid_indices if i < len(prob_changes) and i < len(successes)]
    
    filtered_mse = [mse_values[i] for i in valid_indices]
    filtered_changes = [prob_changes[i] for i in valid_indices]
    filtered_successes = [successes[i] for i in valid_indices]
    
    if len(filtered_mse) == 0:
        print("  Skipped: mse_vs_probability_change.png (no valid data points)")
        return
    
    fig, ax = plt.subplots(figsize=(10, 7))
    
    # Color by success/failure
    colors = ['green' if s else 'red' for s in filtered_successes]
    
    ax.scatter(filtered_mse, filtered_changes, c=colors, s=100, alpha=0.7, edgecolors='black')
    
    # Reference lines
    ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5, label='No change')
    
    ax.set_xlabel('Mean Squared Error (MSE)', fontsize=12)
    ax.set_ylabel('Probability Change (Δ Real Probability)', fontsize=12)
    ax.set_title('Video MSE vs Probability Change (Video-Only Attack)', fontsize=14, fontweight='bold')
    
    # Legend in upper left
    success_patch = mpatches.Patch(color='green', label='Attack Success')
    fail_patch = mpatches.Patch(color='red', label='Attack Failure')
    ax.legend(handles=[success_patch, fail_patch], loc='upper left')
    
    plt.tight_layout()
    plt.savefig(output_path / 'mse_vs_probability_change.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: mse_vs_probability_change.png")


def create_snr_vs_probability_change_scatter(data: Dict, output_path: Path):
    """
    Create standalone scatter plot of Audio SNR vs probability change.
    
    Shows the relationship between audio perturbation quality (SNR) and
    attack effectiveness, with success/failure indicated by color.
    No trend line - just the raw data points.
    """
    arrays = data['arrays']
    
    if 'audio_snr_dbs' not in arrays or 'audio_only_changes' not in arrays:
        print("  Skipped: snr_vs_probability_change.png (missing SNR or probability data)")
        return
    
    snr_values = arrays['audio_snr_dbs']
    prob_changes = arrays['audio_only_changes']
    successes = arrays.get('audio_only_successes', [False] * len(snr_values))
    
    if len(snr_values) == 0:
        print("  Skipped: snr_vs_probability_change.png (no data)")
        return
    
    # Convert successes to boolean list (handles numpy arrays with 1.0/0.0)
    successes_bool = [bool(s) for s in successes]
    
    fig, ax = plt.subplots(figsize=(10, 7))
    
    # Color by success/failure
    colors = ['green' if s else 'red' for s in successes_bool]
    
    ax.scatter(snr_values, prob_changes, c=colors, s=100, alpha=0.7, edgecolors='black')
    
    # Reference lines
    ax.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    
    ax.set_xlabel('Audio SNR (dB) — Higher = Less Perturbed', fontsize=12)
    ax.set_ylabel('Probability Change (Δ Real Probability)', fontsize=12)
    ax.set_title('Audio SNR vs Probability Change', fontsize=14, fontweight='bold')
    
    # Legend in upper left
    success_patch = mpatches.Patch(color='green', label='Attack Success')
    fail_patch = mpatches.Patch(color='red', label='Attack Failure')
    ax.legend(handles=[success_patch, fail_patch], loc='upper left')
    
    plt.tight_layout()
    plt.savefig(output_path / 'snr_vs_probability_change.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: snr_vs_probability_change.png")


def create_summary_dashboard(data: Dict, output_path: Path):
    """Create a comprehensive dashboard with key metrics."""
    fig = plt.figure(figsize=(16, 12))
    gs = GridSpec(3, 3, figure=fig, hspace=0.3, wspace=0.3)
    
    arrays = data['arrays']
    agg = data['aggregate']
    
    # 1. ASR comparison (top left)
    ax1 = fig.add_subplot(gs[0, 0])
    video_asr = agg.get('video_only_success_rate', 0) * 100
    audio_asr = agg.get('audio_only_success_rate', 0) * 100
    combined_asr = agg.get('combined_success_rate', 0) * 100
    bars = ax1.bar(['Video', 'Audio', 'Combined'], [video_asr, audio_asr, combined_asr],
                   color=['#3498db', '#2ecc71', '#e74c3c'], edgecolor='black')
    ax1.set_ylabel('ASR (%)')
    ax1.set_title('Attack Success Rate', fontweight='bold')
    ax1.set_ylim(0, 110)
    for bar, val in zip(bars, [video_asr, audio_asr, combined_asr]):
        ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2, f'{val:.0f}%', 
                 ha='center', fontsize=10, fontweight='bold')
    
    # 2. Confidence change comparison (top middle)
    ax2 = fig.add_subplot(gs[0, 1])
    means = [
        agg.get('video_only_change_mean', 0),
        agg.get('audio_only_change_mean', 0),
        agg.get('combined_change_mean', 0)
    ]
    stds = [
        agg.get('video_only_change_std', 0),
        agg.get('audio_only_change_std', 0),
        agg.get('combined_change_std', 0)
    ]
    x_pos = [0, 1, 2]
    ax2.bar(x_pos, means, yerr=stds, color=['#3498db', '#2ecc71', '#e74c3c'], 
            edgecolor='black', capsize=5)
    ax2.set_xticks(x_pos)
    ax2.set_xticklabels(['Video', 'Audio', 'Combined'])
    ax2.set_ylabel('Δ Confidence')
    ax2.set_title('Mean Confidence Change (±σ)', fontweight='bold')
    ax2.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    
    # 3. Best attack pie (top right)
    ax3 = fig.add_subplot(gs[0, 2])
    sizes = [
        int(agg.get('video_best_count', 0)),
        int(agg.get('audio_best_count', 0)),
        int(agg.get('combined_best_count', 0))
    ]
    if sum(sizes) > 0:
        ax3.pie(sizes, labels=['Video', 'Audio', 'Combined'], 
                colors=['#3498db', '#2ecc71', '#e74c3c'],
                autopct='%1.0f%%', startangle=90)
    ax3.set_title('Best Attack Distribution', fontweight='bold')
    
    # 4. Probability trajectory (middle row, spans 2 columns)
    ax4 = fig.add_subplot(gs[1, :2])
    if 'original_probs' in arrays:
        n = len(arrays['original_probs'])
        x = np.arange(1, n + 1)
        ax4.plot(x, arrays['original_probs'], 'ko-', label='Original', markersize=5)
        ax4.plot(x, arrays['video_only_probs'], 's--', color='#3498db', label='Video', markersize=5)
        ax4.plot(x, arrays['audio_only_probs'], '^--', color='#2ecc71', label='Audio', markersize=5)
        ax4.plot(x, arrays['combined_probs'], 'D-', color='#e74c3c', label='Combined', markersize=5)
        ax4.axhline(y=0.5, color='orange', linestyle='--', alpha=0.7)
        ax4.fill_between(x, 0.5, 1, alpha=0.1, color='green')
        ax4.set_xlabel('Sample Index')
        ax4.set_ylabel('P(real)')
        ax4.set_title('Probability Trajectory', fontweight='bold')
        ax4.legend(loc='upper right', ncol=4, fontsize=8)
        ax4.set_ylim(0, 1.05)
    
    # 5. Perturbation summary (middle right)
    ax5 = fig.add_subplot(gs[1, 2])
    metrics = ['Video L∞', 'Video L2', 'Audio L∞', 'Audio SNR']
    values = [
        agg.get('video_linf_mean', 0),
        agg.get('video_l2_mean', 0) / 100,  # Scale down for visibility
        agg.get('audio_linf_mean', 0),
        agg.get('audio_snr_mean', 0) / 100  # Scale down
    ]
    colors = ['#3498db', '#3498db', '#2ecc71', '#2ecc71']
    bars = ax5.barh(metrics, values, color=colors, edgecolor='black')
    ax5.set_xlabel('Normalized Value')
    ax5.set_title('Perturbation Metrics', fontweight='bold')
    
    # 6. Timing breakdown (bottom left)
    ax6 = fig.add_subplot(gs[2, 0])
    times = [
        np.mean(arrays.get('video_times', [0])),
        np.mean(arrays.get('audio_times', [0]))
    ]
    ax6.pie(times, labels=[f'Video\n{times[0]:.1f}s', f'Audio\n{times[1]:.1f}s'],
            colors=['#3498db', '#2ecc71'], autopct='%1.0f%%', startangle=90)
    ax6.set_title('Time Distribution', fontweight='bold')
    
    # 7. Key statistics text (bottom middle)
    ax7 = fig.add_subplot(gs[2, 1])
    ax7.axis('off')
    stats_text = f"""
    KEY STATISTICS
    ══════════════════════════
    Samples Tested: {len(data['samples'])}
    
    Success Rates:
      • Video-Only:  {video_asr:.1f}%
      • Audio-Only:  {audio_asr:.1f}%
      • Combined:    {combined_asr:.1f}%
    
    Best Overall: {'Combined' if combined_asr >= max(video_asr, audio_asr) else ('Video' if video_asr >= audio_asr else 'Audio')}
    
    Avg Total Time: {np.mean(arrays.get('total_times', [0])):.1f}s/sample
    """
    ax7.text(0.1, 0.9, stats_text, transform=ax7.transAxes, fontsize=11,
             verticalalignment='top', fontfamily='monospace',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # 8. Confidence change histogram (bottom right)
    ax8 = fig.add_subplot(gs[2, 2])
    if 'combined_changes' in arrays:
        ax8.hist(arrays['combined_changes'], bins=10, color='#e74c3c', 
                 edgecolor='black', alpha=0.7)
        ax8.axvline(x=0, color='gray', linestyle='--')
        ax8.axvline(x=np.mean(arrays['combined_changes']), color='blue', 
                    linestyle='--', label=f'Mean: {np.mean(arrays["combined_changes"]):.3f}')
        ax8.set_xlabel('Confidence Change')
        ax8.set_ylabel('Frequency')
        ax8.set_title('Combined Attack Distribution', fontweight='bold')
        ax8.legend(fontsize=8)
    
    plt.suptitle('Audio-Visual Adversarial Attack Results Dashboard', 
                 fontsize=16, fontweight='bold', y=1.02)
    
    plt.savefig(output_path / 'summary_dashboard.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: summary_dashboard.png")


def create_all_visualizations(data: Dict, output_path: Path, results_dir: Path = None):
    """Generate all visualizations."""
    print("\nGenerating visualizations...")
    
    output_path.mkdir(parents=True, exist_ok=True)
    
    create_asr_bar_chart(data, output_path)
    create_confidence_change_boxplot(data, output_path)
    create_probability_trajectory_plot(data, output_path)
    create_perturbation_analysis_plot(data, output_path)
    create_perturbation_vs_effectiveness_scatter(data, output_path)
    create_best_attack_pie_chart(data, output_path)
    create_timing_analysis_plot(data, output_path)
    create_summary_dashboard(data, output_path)
    
    # New visualizations
    create_snr_vs_probability_change_scatter(data, output_path)
    if results_dir:
        create_mse_vs_probability_change_scatter(data, output_path, results_dir)
    
    print(f"\nAll visualizations saved to: {output_path.absolute()}")


def main():
    parser = argparse.ArgumentParser(description="Generate visualizations from attack results")
    parser.add_argument("--results-file", type=str, default=None,
                        help="Path to audiovisualresults.txt file")
    parser.add_argument("--results-dir", type=str, default="./final_audiovisualattack",
                        help="Directory containing audiovisualresults.txt")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory for visualizations (default: same as results)")
    
    args = parser.parse_args()
    
    # Determine results file path
    if args.results_file:
        results_path = Path(args.results_file)
        results_dir = results_path.parent
    else:
        results_dir = Path(args.results_dir)
        results_path = results_dir / "audiovisualresults.txt"
    
    if not results_path.exists():
        print(f"Error: Results file not found: {results_path}")
        print("Run final_audio_visual_attack.py first to generate results.")
        sys.exit(1)
    
    # Determine output directory
    if args.output_dir:
        output_path = Path(args.output_dir)
    else:
        output_path = results_path.parent / "visualizations"
    
    print("=" * 60)
    print("VISUALIZATION GENERATOR")
    print("=" * 60)
    print(f"\nReading results from: {results_path}")
    print(f"Output directory: {output_path}")
    
    # Parse results
    data = parse_results_file(results_path)
    
    print(f"\nFound {len(data['samples'])} samples")
    print(f"Configuration parameters: {len(data['config'])}")
    print(f"Aggregate statistics: {len(data['aggregate'])}")
    print(f"Data arrays: {len(data['arrays'])}")
    
    # Generate visualizations (pass results_dir for MSE calculation)
    create_all_visualizations(data, output_path, results_dir)
    
    print("\nDone!")


if __name__ == "__main__":
    main()
